### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by PLUCS2** [sebastianss1/Artsee#2]
- [x] What are the options for the reasons for using category options? (Specify for inclusion) 
- [x] Just needs an `artist_id` not an artist name on the Artworks table
- [x] Split dimensions on the Artworks table to a height and width as floats (store as CM) - you will do the conversion (so that the dimensions can be shown in both cm and inches) before displaying to the user
- [x] Make a mediums table (with the possible mediums) and have the artworks table hold a `medium_id` (this will make filtering and searching easier 
- [x] What is `category` on the Artworks Table? 
- [ ] There are two options for artwork price - a price, or "contact for price" - how do you plan on handling this? 
- [ ] I did not see condition - where was that and what are the options for that category? 
- [ ] The artworks also have a unique option - do you plan on implementing this? 
- [ ] What are the options for signature? On the Artworks table 
- [x] Certificate of auth should be a boolean 
- [x] Artists that are dead should have a death year as well 
- [x] I would not do `nationality` on the Artists table (or at all) - implement it as a BONUS if you would like 
- [x] Artists can be associated with many Galleries, and Galleries can be associated with many Artists 
- [ ] Follows should be polymorphic (you can follow a Gallery or an Artist) 
- [x] Likes should NOT be polymorphic as you can only like an Artwork (as far as I can tell) 
- [x] You should have a shows table as a BONUS 
- [ ] No need to have a website url on the galleries (as a BONUS you could have the Contact section of the Gallery page that shows the website url, phone, address, and location on a map) 

Nice work! Let me know if you have any questions

**Comment by sebastianss1** [comment]
Hi Paloma, responding to a few of your questions and comments -

> * [x]  What are the options for the reasons for using category options? (Specify for inclusion)
_added to table_
> * [x]  Just needs an `artist_id` not an artist name on the Artworks table
_done_
> * [x]  Split dimensions on the Artworks table to a height and width as floats (store as CM) - you will do the conversion (so that the dimensions can be shown in both cm and inches) before displaying to the user
_done_
> * [x]  Make a mediums table (with the possible mediums) and have the artworks table hold a `medium_id` (this will make filtering and searching easier
_done. let me know your thoughts_
> * [x]  What is `category` on the Artworks Table?
_changed this up - because at the top of the page under the title there's a medium, but i added that as 'description' in my table, then under the artwork there's an actual medium section_
> * [ ]  There are two options for artwork price - a price, or "contact for price" - how do you plan on handling this?
_what do you think? there's a CMS for galleries that allows them to toggle between showing prices / having buy now / contact for price. I was thinking to just manually change these for different artwork examples? I'm not sure here _
> * [ ]  I did not see condition - where was that and what are the options for that category?
_again, the backend has many different options that can be toggled / untoggled / are not relevant. Some artworks have conditions_
> * [ ]  The artworks also have a unique option - do you plan on implementing this?
_Same as above. All artworks have different options _
> * [ ]  What are the options for signature? On the Artworks table
_On the CMS for galleries, I'm pretty sure it's a text area where you can add whatever you like / is relevant to the artwork (there are all diff kinds of signatures)_
> * [x]  Certificate of auth should be a boolean
_done_
> * [x]  Artists that are dead should have a death year as well
_done_
> * [x]  I would not do `nationality` on the Artists table (or at all) - implement it as a BONUS if you would like
_done_
> * [x]  Artists can be associated with many Galleries, and Galleries can be associated with many Artists
_added to the bottom of artists / galleries tables_
> * [ ]  Follows should be polymorphic (you can follow a Gallery or an Artist)
_done_
> * [x]  Likes should NOT be polymorphic as you can only like an Artwork (as far as I can tell)
_done. removed likeable_
> * [x]  You should have a shows table as a BONUS
_done_
> * [ ]  No need to have a website url on the galleries (as a BONUS you could have the Contact section of the Gallery page that shows the website url, phone, address, and location on a map)
_done_
> 
> Nice work! Let me know if you have any questions
